package sql

// alter_test.go: ALTER COLUMN TYPE [USING], the SET STORAGE/STATISTICS
// no-ops, ADD COLUMN of an identity column, and the primary-key
// replacement — through SQL, so the parse, the USING evaluation and the
// CHECK re-validation are exercised together with the engine rewrite.

import (
	"strings"
	"testing"
)

func TestAlterColumnTypeSQL(t *testing.T) {
	d := openDB(t)
	exec(t, d, `create table t (id int primary key, price float, code text, qty text)`)
	exec(t, d, `create index t_price on t (price)`)
	exec(t, d, `insert into t values (1, 9.5, 'A1', '12'), (2, 10.5, 'B2', null), (3, 2.25, 'C3', '7')`)

	// Automatic cast, both spellings; the index follows the new type.
	exec(t, d, `alter table t alter column price type bigint`)
	wantRows(t, d, `select id, price from t where price >= 10 order by price`, [][]any{{int64(1), int64(10)}, {int64(2), int64(10)}})
	exec(t, d, `alter table t alter price set data type double precision`)
	wantRows(t, d, `select price from t where id = 3`, [][]any{{2.0}})

	// text -> int has no automatic cast: Postgres's error and hint.
	err := execErr(t, d, `alter table t alter column qty type int`)
	if !strings.Contains(err, `column "qty" cannot be cast automatically to type bigint`) {
		t.Fatalf("no-cast error: %s", err)
	}
	// USING converts it, may read other columns, and may fill NULLs.
	exec(t, d, `alter table t alter column qty type int using coalesce(qty::int, id * 100)`)
	wantRows(t, d, `select id, qty from t order by id`, [][]any{{int64(1), int64(12)}, {int64(2), int64(200)}, {int64(3), int64(7)}})

	// A bad value fails the whole statement, leaving the column as it was.
	exec(t, d, `insert into t values (4, 1, 'xx', 1)`)
	execErr(t, d, `alter table t alter column code type int using code::int`)
	wantRows(t, d, `select code from t where id = 4`, [][]any{{"xx"}})

	// varchar(n): shrinking below a stored value fails; widening works.
	if err := execErr(t, d, `alter table t alter column code type varchar(1)`); !strings.Contains(err, "value too long") {
		t.Fatalf("shrink: %s", err)
	}
	exec(t, d, `alter table t alter column code type varchar(8)`)

	// USING admits no subqueries, like a CHECK.
	if err := execErr(t, d, `alter table t alter column qty type int using (select 1)`); !strings.Contains(err, "cannot use subquery in transform expression") {
		t.Fatalf("subquery in USING: %s", err)
	}
	if err := execErr(t, d, `alter table t alter column nope type int`); !strings.Contains(err, "does not exist") {
		t.Fatalf("missing column: %s", err)
	}
}

func TestAlterColumnTypeRechecksConstraints(t *testing.T) {
	d := openDB(t)
	exec(t, d, `create table t (id int primary key, v float check (v <> 2))`)
	exec(t, d, `insert into t values (1, 1.6), (2, 3)`)
	// 1.6 rounds to 2 under bigint, which the CHECK forbids.
	err := execErr(t, d, `alter table t alter column v type bigint`)
	if !strings.Contains(err, `check constraint "t_v_check" of relation "t" is violated by some row`) {
		t.Fatalf("check re-validation: %s", err)
	}
	wantRows(t, d, `select v from t order by id`, [][]any{{1.6}, {3.0}})
}

func TestAlterColumnNoops(t *testing.T) {
	d := openDB(t)
	exec(t, d, `create table t (id int primary key, body text)`)
	exec(t, d, `alter table t alter column body set storage external`)
	exec(t, d, `alter table t alter body set statistics 500`)
	exec(t, d, `alter table t alter body set statistics -1`)
	if err := execErr(t, d, `alter table t alter column nope set storage plain`); !strings.Contains(err, "does not exist") {
		t.Fatalf("no-op on missing column: %s", err)
	}
}

func TestAddIdentityColumnSQL(t *testing.T) {
	d := openDB(t)
	exec(t, d, `create table t (code text primary key, note text)`)
	exec(t, d, `insert into t values ('b', 'x'), ('a', 'y'), ('c', 'z')`)
	exec(t, d, `alter table t add column id bigint generated by default as identity`)
	exec(t, d, `alter table t add column n serial`)
	wantRows(t, d, `select code, id, n from t order by code`, [][]any{
		{"a", int64(1), int64(1)}, {"b", int64(2), int64(2)}, {"c", int64(3), int64(3)}})
	exec(t, d, `insert into t (code) values ('d')`)
	wantRows(t, d, `select id, n from t where code = 'd'`, [][]any{{int64(4), int64(4)}})
}

func TestReplacePrimaryKeySQL(t *testing.T) {
	d := openDB(t)
	exec(t, d, `create table t (id int primary key, email text, org int)`)
	exec(t, d, `create unique index t_email on t (email)`)
	exec(t, d, `insert into t values (1, 'z@x', 10), (2, 'a@x', 10), (3, 'm@x', 20)`)

	exec(t, d, `alter table t drop constraint t_pkey, add primary key (org, email)`)
	// Key order now drives an unordered scan.
	wantRows(t, d, `select id from t`, [][]any{{int64(2)}, {int64(1)}, {int64(3)}})
	// The new key rejects duplicates; the old one no longer does.
	if err := execErr(t, d, `insert into t values (9, 'a@x', 10)`); !strings.Contains(err, "duplicate") {
		t.Fatalf("new key: %s", err)
	}
	exec(t, d, `insert into t values (1, 'q@x', 30)`)
	// The unique index still enforces, through rebuilt entries.
	if err := execErr(t, d, `insert into t values (7, 'm@x', 40)`); !strings.Contains(err, "unique") {
		t.Fatalf("unique index after re-key: %s", err)
	}
	// Named ADD CONSTRAINT form, back to a single column: id 1 now repeats.
	err := execErr(t, d, `alter table t drop constraint t_pkey, add constraint anything primary key (id)`)
	if !strings.Contains(err, `could not create unique index "t_pkey"`) {
		t.Fatalf("duplicate on re-key: %s", err)
	}
	exec(t, d, `delete from t where email = 'q@x'`)
	exec(t, d, `alter table t drop constraint t_pkey, add constraint anything primary key (id)`)
	wantRows(t, d, `select id from t`, [][]any{{int64(1)}, {int64(2)}, {int64(3)}})

	for q, want := range map[string]string{
		`alter table t add primary key (email)`:                                 `multiple primary keys for table "t" are not allowed`,
		`alter table t drop constraint other, add primary key (email)`:          `multiple primary keys for table "t" are not allowed`,
		`alter table t drop constraint if exists t_pkey, add primary key (org)`: "cannot be combined",
		`alter table t drop constraint t_pkey, add unique (org)`:                "",
		`alter table t drop constraint t_pkey`:                                  `cannot drop constraint "t_pkey"`,
	} {
		if err := execErr(t, d, q); !strings.Contains(err, want) {
			t.Fatalf("%s\n  got:  %s\n  want: %s", q, err, want)
		}
	}
}
