package sql

import (
	"reflect"
	"testing"
)

// pg_attrdef carries declared column defaults (adbin holds the stored
// literal text; pg_get_expr surfaces it as-is), atthasdef gates it in
// pg_attribute, and identity columns report through attidentity — the
// pieces psql's \d Default column reads.

func TestPgAttrdef(t *testing.T) {
	d := openDB(t)
	exec(t, d, `create table items (
		id int primary key,
		qty int default 1,
		tag text default 'new',
		note text)`)

	res := exec(t, d, `select adrelid, adnum, adbin from pg_attrdef order by adnum`)
	oid := exec(t, d, `select 'items'::regclass`).Rows[0][0]
	want := [][]any{
		{oid, int64(2), "1"},
		{oid, int64(3), "'new'"},
	}
	if !reflect.DeepEqual(res.Rows, want) {
		t.Fatalf("pg_attrdef rows: %v", res.Rows)
	}

	// The exact join psql 17 issues for \d's Default column.
	res = exec(t, d, `SELECT a.attname,
		(SELECT pg_catalog.pg_get_expr(d.adbin, d.adrelid, true)
		 FROM pg_catalog.pg_attrdef d
		 WHERE d.adrelid = a.attrelid AND d.adnum = a.attnum AND a.atthasdef),
		a.attnotnull
		FROM pg_catalog.pg_attribute a
		WHERE a.attrelid = 'items'::regclass AND a.attnum > 0 AND NOT a.attisdropped
		ORDER BY a.attnum`)
	want = [][]any{
		{"id", nil, true},
		{"qty", "1", false},
		{"tag", "'new'", false},
		{"note", nil, false},
	}
	if !reflect.DeepEqual(res.Rows, want) {
		t.Fatalf("psql default column: %v", res.Rows)
	}
}

// TestPgAttrIdentity: identity columns surface as attidentity 'd'
// (GENERATED BY DEFAULT), not as pg_attrdef rows — Postgres' split.
func TestPgAttrIdentity(t *testing.T) {
	d := openDB(t)
	exec(t, d, `create table ev (id serial primary key, name text)`)

	res := exec(t, d, `select a.attname, a.attidentity, a.atthasdef
		from pg_attribute a
		where a.attrelid = 'ev'::regclass and a.attnum > 0 order by a.attnum`)
	want := [][]any{
		{"id", "d", false},
		{"name", "", false},
	}
	if !reflect.DeepEqual(res.Rows, want) {
		t.Fatalf("identity attribute: %v", res.Rows)
	}
	if res := exec(t, d, `select count(*) from pg_attrdef`); !reflect.DeepEqual(res.Rows, [][]any{{int64(0)}}) {
		t.Fatalf("identity must not add pg_attrdef rows: %v", res.Rows)
	}
}
