package sql

// identity_test.go: SERIAL and GENERATED BY DEFAULT AS IDENTITY —
// parse forms, insert-time allocation through the SQL layer, explicit
// values bumping the counter, and catalog reporting.

import (
	"reflect"
	"strings"
	"testing"

	"github.com/rohanthewiz/bytdb"
)

func TestSerialInsert(t *testing.T) {
	d := openDB(t)
	exec(t, d, `create table users (id serial primary key, name text)`)

	// Column-list inserts omit the id; each row draws the next value.
	exec(t, d, `insert into users (name) values ('ada'), ('grace')`)
	// An explicit id inserts as given and bumps the counter past itself.
	exec(t, d, `insert into users values (10, 'alan')`)
	exec(t, d, `insert into users (name) values ('edsger')`)
	// A full-arity insert with NULL in the identity column also draws.
	exec(t, d, `insert into users values (null, 'barbara')`)

	res := exec(t, d, `select id, name from users order by id`)
	want := [][]any{
		{int64(1), "ada"}, {int64(2), "grace"}, {int64(10), "alan"},
		{int64(11), "edsger"}, {int64(12), "barbara"},
	}
	if !reflect.DeepEqual(res.Rows, want) {
		t.Fatalf("got %v, want %v", res.Rows, want)
	}
}

func TestGeneratedIdentity(t *testing.T) {
	d := openDB(t)
	exec(t, d, `create table t (id int generated by default as identity primary key, v text)`)
	exec(t, d, `insert into t (v) values ('a'), ('b')`)
	res := exec(t, d, `select id from t order by id`)
	if !reflect.DeepEqual(res.Rows, [][]any{{int64(1)}, {int64(2)}}) {
		t.Fatalf("got %v", res.Rows)
	}

	// ALWAYS would promise a restriction we don't enforce.
	_, err := d.Exec(`create table t2 (id int generated always as identity primary key)`)
	if err == nil || !strings.Contains(err.Error(), "BY DEFAULT") {
		t.Fatalf("GENERATED ALWAYS: got %v, want a not-supported error naming BY DEFAULT", err)
	}
	// Identity needs an int column.
	_, err = d.Exec(`create table t3 (id text generated by default as identity primary key)`)
	if err == nil || !strings.Contains(err.Error(), "int") {
		t.Fatalf("text identity: got %v, want a type error", err)
	}
	// NULL contradicts what identity implies.
	_, err = d.Exec(`create table t4 (id serial null primary key)`)
	if err == nil || !strings.Contains(err.Error(), "conflicting") {
		t.Fatalf("serial null: got %v, want a conflict error", err)
	}
}

func TestSerialAliases(t *testing.T) {
	d := openDB(t)
	for _, typ := range []string{"serial", "bigserial", "smallserial", "serial2", "serial4", "serial8"} {
		exec(t, d, `create table t (id `+typ+` primary key, v text)`)
		exec(t, d, `insert into t (v) values ('x')`)
		res := exec(t, d, `select id from t`)
		if !reflect.DeepEqual(res.Rows, [][]any{{int64(1)}}) {
			t.Fatalf("%s: got %v", typ, res.Rows)
		}
		exec(t, d, `drop table t`)
	}
}

// TestSerialIdentityNotNull: the identity column rejects UPDATE to
// NULL, and the catalog reports it non-nullable with a serial-style
// default.
func TestSerialIdentityNotNull(t *testing.T) {
	d := openDB(t)
	exec(t, d, `create table t (id int primary key, n serial)`)
	exec(t, d, `insert into t (id) values (1)`)
	if _, err := d.Exec(`update t set n = null where id = 1`); err == nil ||
		!strings.Contains(err.Error(), "not-null") {
		t.Fatalf("update serial to NULL: got %v, want a not-null violation", err)
	}

	res := exec(t, d, `select column_name, column_default, is_nullable
		from information_schema.columns where table_name = 't' order by ordinal_position`)
	want := [][]any{
		{"id", nil, "NO"},
		{"n", "nextval('t_n_seq'::regclass)", "NO"},
	}
	if !reflect.DeepEqual(res.Rows, want) {
		t.Fatalf("catalog rows %v, want %v", res.Rows, want)
	}
	if res.Types[1] != bytdb.TString {
		t.Fatalf("column_default type %v", res.Types[1])
	}
}
